### ISSUE TITLE
Form Project Summary

### ISSUE THREAD

**Issue by kemitchell** [kemitchell/switchmode#1]
- [ ] Open Project
- [ ] Closed Project
- [ ] worked example

**Comment by jeremy-w** [comment]
Example scenarios would help a lot. The licensing bits get kind of hairy.

**Comment by kemitchell** [comment]
@jeremy-w Absolutely.

The hope is that templates for the summaries will spare most folks actually worrying about the "API" of the master terms. I'd like just a bit more feedback on the main terms before I invest time in the templates. But they should write pretty quick when they write.
