### ISSUE TITLE
Techie: Missing object of verb "disclose" in latter half of Secrets, Collaborating

### ISSUE THREAD

**Issue by jeremy-w** [kemitchell/switchmode#10]
Presumably just need to add _Secrets_ in 5 and on:

5.  _Developer_ may disclose only to receive technical support for, report a possible bug in, or to propose or discuss changes to, _Open Software_.

6.  The _Open Software_ must be _Software_ that a _Project_ _Utilizes_ or potentially _Utilizes_, or _Open Software_ used or potentially used to operate or develop _Project_ _Software_.

7.  _Developer_ may disclose by private message to an _Open Software_ developer, or by message to a public mailing list, bug tracking system, or revision control system.

(Pretend that's all block quoted. Too annoying to markup on mobile.)

**Comment by kemitchell** [comment]
Another great nit!
