### ISSUE TITLE
Techie: Secrets: "information from" reads weird

### ISSUE THREAD

**Issue by jeremy-w** [kemitchell/switchmode#12]
Is the intention "information shared by"? Or "provided by"? Either reads better.

Both also avoid a confusing bit here:

> _Information Marked Confidential_ from either party

This risks reading like "information either party has marked confidential" (there have been enough weird prepositions that "from" for "by" seems feasible) rather than "either party's shared _Info Marked Confidential_."

**Comment by kemitchell** [comment]
The intent was something like "Information Marked Confidential _provided by_ either party". I'll try to improve.

**Comment by kemitchell** [comment]
On second look, some of the items in the list had verbs, and some did not. A list of items of different kinds is always a red flag!

I ended up going with "share", but in the paragraph, rather than in the list. Here's where I ended up:

> ### Secrets<a id="Secrets"></a>
>
> The confidentiality obligations of these terms apply to the **Secrets** that the parties share with one another. _Secrets_ include these kinds of information, when not _Publicly Available_:
>
> 1.  _Information Marked Confidential_
>
> 2.  _Business Information_
>
> 3.  _Personal Information_
> 
> 4.  the fact that _Company_ is _Developer_'s client for work on any _Project_
>
> 5.  information about any _Closed Project_
>
> 6.  information about any _Company_ product or service that _Utilizes_ or motivates any _Open Project_
>
> 7.  information about the _Software_, services, systems, and other tools that _Company_ uses

**Comment by jeremy-w** [comment]
That is better. 4, 6, and 7 are weirdly asymmetric: They protect the company from dev but not vice-versa. Any reason not to make those symmetric?

--
Jeremy W. Sherman
http://jeremywsherman.com/
