### ISSUE TITLE
Credit Jeremy

### ISSUE THREAD

**Issue by kemitchell** [kemitchell/switchmode#13]
@jeremy-w, you've sent some really great issues. And a lot of them! On a Friday night!

Alas, issues don't get you in the commit log. Let's figure something else out. Are you comfortable with any of these?

- Mention by name in release notes for the next draft.
- Mention by name, with notes on contribution, in README.
- Mention by name, with notes on contribution, in a separate, less visible file, say `THANKS`.
- Thanks on Twitter.
- Other approaches you might think of.

If any of these are okay, please let me know how you'd like to be mentioned---by name, by GitHub handle, with a company affiliation, or some combination.

I've done a lot of work on this, but whether it succeeds as a project has precious little to do with my bit. It has everything to do with folks making it better, making it their own, and using it to make opportunities.

**Comment by jeremy-w** [comment]
I'm comfortable with all of them.

A THANKS/CONTRIBUTORS file sounds like a good approach. Mentioning it in the README alongside the encouragement for the reader to contribute keeps the readme short and focused on the project.

Feel free to use this to promote the common form.

For mention, I think name + homepage would work well:

Jeremy W. Sherman <https://jeremywsherman.com>

I wouldn't have thought to leave any issues without the strong encouragement to provide feedback in the README and CONTRIBUTING files. You did great work in making it clear how others can help. :)
--
Jeremy W. Sherman
http://jeremywsherman.com/

**Comment by kemitchell** [comment]
I'll put together a PR and mention you in it.
