### ISSUE TITLE
Techie: Mangled sentence in Agreement Term

### ISSUE THREAD

**Issue by jeremy-w** [kemitchell/switchmode#7]
Has:

> This agreement will continue until one year has passed since _Developer_ there was any ongoing _Project_.

Guessing intended:

> This agreement will continue until one year has passed since there was any ongoing _Project_ agreed by _Developer_ and _Company_.

**Comment by kemitchell** [comment]
I've fixed this a little differently than you proposed, but you were absolutely right that it needed fixing.
