### ISSUE TITLE
Techie: Dictionary: Info marked confidential [nit]

### ISSUE THREAD

**Issue by jeremy-w** [kemitchell/switchmode#8]
> 9.  **Information Marked Confidential** means information that is not _Publicly Available_, disclosed in materials marked or identified in writing as "Secret", "Confidential", "Proprietary", or similar.

Expect "and is disclosed" rather than a comma.

**Comment by kemitchell** [comment]
Yup, you're right. That's a quirk of personal style showing through where it shouldn't.
