### ISSUE TITLE
Techie: Weird preposition: against the terms of this agreement

### ISSUE THREAD

**Issue by jeremy-w** [kemitchell/switchmode#9]
"against the terms of this agreement" read weird every time. I'd expect "contrary to" rather than "against". Dunno if this is a term of art, though.

**Comment by kemitchell** [comment]
No, it's not a term of art.

The standard lawyer speak is "in breach of this agreement". I'd like to find a plainer, more natural way to say that, and use it consistently.

**Comment by kemitchell** [comment]
I think we can avoid the awkward phrase by choosing ... to drop it! Clear from context, methinks.

**Comment by jeremy-w** [comment]
Yes, clear.

Could probably fold the first two assignment sentences together to avoid going "can't except some exceptions, can't, ok now those exceptions", which pushes the exceptions a bit away from their first mention.

--
Jeremy W. Sherman
http://jeremywsherman.com/
